name: ginkgo
description: A Ğinkgo light wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2-SNAPSHOT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_displaymode: ^0.6.0
  easy_localization: ^3.0.1
  hive: ^2.2.3
  url_launcher: ^6.1.7
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.2
  http: ^0.13.5
  easy_logger: ^0.0.2
  qr_flutter: ^4.0.0
  introduction_screen: ^3.1.6
  responsive_framework: ^0.2.0
  #durt: ^0.1.7
  durt:
    path: ../durt
    #git:
    #  url: https://git.duniter.org/vjrj/durt
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  shared_preferences: ^2.0.18
  vibration: ^1.7.6
  clipboard: ^0.1.3
  # See: https://github.com/leocavalcante/encrypt/issues/314
  encrypt: 5.0.1
  universal_html: ^2.0.9
  fl_chart: ^0.63.0
  json_annotation: ^4.8.0
  flutter_slidable: ^3.0.0
  sentry_flutter: ^7.8.0
  copy_with_extension: ^5.0.2
  timeago: ^3.5.0
  once: ^1.5.1
  pattern_lock: ^2.0.0
  package_info_plus: ^4.1.0
  share_plus: ^7.1.0
  sentry_logging: ^7.8.0
  pwa_install: ^0.0.5
  file_saver: ^0.2.1
  filesystem_picker: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.14
  awesome_notifications: ^0.7.5-dev.3
  cron: ^0.5.1
  barcode_scan2: ^4.2.4
  jsqr: ^0.1.4
  web_browser_detect: ^2.0.3
  tuple: ^2.0.1
  infinite_scroll_pagination: ^4.0.0
  easy_debounce: ^2.0.3
  tutorial_coach_mark: ^1.2.8
  lehttp_overrides: ^1.0.2
  feedback_gitlab: ^2.2.0
  connectivity_wrapper: ^1.1.3
  rxdart: ^0.27.7
  fast_image_resizer: ^0.0.2
  toggle_switch: ^2.1.0
  fast_base58: ^0.2.1
  crypto: ^3.0.3
  flutter_nfc_kit: ^3.3.3
  ndef: ^0.3.1
  uni_links: ^0.5.1
  feedback: ^2.6.0
  sentry_dart_plugin: ^1.5.0
  check_vpn_connection: ^0.0.2
  provider: ^6.0.5
  we_slide: ^2.4.0
  workmanager: ^0.5.1
  get_it: ^7.6.4
  l10n_esperanto: ^2.0.9
  collection: ^1.17.2
  envied: ^0.5.3
  polkadart: ^0.1.0
  polkadart_keyring: ^0.3.0
  ferry: ^0.11.3-dev.0+1
  gql_http_link: ^0.4.5
  substrate_bip39: ^0.2.0
  pointycastle: ^3.9.0
  bip39_multi_nullsafety: ^1.0.7
  material_symbols_icons: ^4.2719.3
  text_scroll: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.6.1
  copy_with_extension_gen: any
  envied_generator: ^0.5.3
  ferry_generator: ^0.6.1

# source: https://stackoverflow.com/a/75332857/8301867
dependency_overrides:
  #web_socket_channel: 2.2.0
  intl: ^0.18.1
  analyzer: ^6.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/img/gbrevedot.svg
    - assets/img/gbrevedot.png
    - assets/img/gbrevedot_color.png
    - assets/img/gbrevedot_alt.svg
    - assets/img/gbrevedot_alt.png
    - assets/.env.development
    - assets/env.production.txt
    - assets/env-test.production.txt
    - assets/img/undraw_intro_1.png
    - assets/img/undraw_intro_2.png
    - assets/img/undraw_intro_3.png
    - assets/img/undraw_intro_4.png
    - assets/img/undraw_intro_5.png
    - assets/img/chip.svg
    - assets/img/logo.png
    - assets/img/favicon.png
    - assets/img/logo-duniter.png
    - assets/img/logo-cesium.png
    - assets/tx.json
    - assets/gva-tx.json
    - assets/img/animated-bell.gif
    - assets/img/pos.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: ginkgo
  org: comunes
  url: https://sentry.comunes.org
  #wait_for_processing: false
  #log_level: error # possible values: trace, debug, info, warn, error
  log_level: info # possible values: trace, debug, info, warn, error
  # release:  default: name@version from pubspec
  #web_build_path: ...
  # commits: auto
  ignore_missing: true

